.TH DMENU-FILE 1 dmenu-file
.SH NAME
dmenu-file \- dmenu file \- select a file with dmenu
.SH SYNOPSIS
.B dmenu-file
[path]
.SH DESCRIPTION
.B dmenu-file
when called will call dmenu with its items being each of the files or directories in the directory passed as the one and only argument or the current directory if no argument is passed. If a file is selected it prints the selected file and exits with success. If a directory is selected then it behaves as if it was called again with the argument passed being the selected directory and continues to do so until a file or non\-existant file or directory is called. If a non\-existant file or directory is selected then that is printed to standard output and it exits with a error code of 2. If dmenu is exited (escape key is pressed) then nothing is printed to standard output and it exits with an error code of 1. Furthermore, if a file or non-existnent path was provided as the sole argument in the first place then that it will be treated as if it had been selected in the dmenu list as described aboved.
.SH AUTHORS
Written by Zachary Schlitt <ztschlitt@gmail.com>
.SH LICENSE
MIT
.SH SEE ALSO
.BR dmenu (1)
